In [1]:
import pandas as pd

df = pd.read_excel(
    "../data/raw/orders.xlsx"
)

print(df.shape)

df.head()

(4999, 30)

,createdAt,deliveryDate,orderTime,orderNumber,callingAgentId,callingAgentName,hubId,hubName,customerId,shopType,...,deliveredQty,deliveredTime,orderStatus,skuStatus,orderToDeliveryTime,deliveryTimeSlot,cancellationReason,brand,category,subCategory
0,2026-01-31,2026-02-02,23:55:02,26013101482,NaN,NaN,HB011,Rapid Enterprises,USR-169747,General B,...,1,2026-02-02 16:42:00,Delivered,DELIVERED,"1 days, 16 hours, 47 minutes",2026-02-02 09:00:00,NaN,Rajnigandha,Pan Masala,Premium Pan Masala
1,2026-01-31,2026-02-02,23:46:26,26013101481,NaN,NaN,HB011,Rapid Enterprises,USR-169429,Wholesaler,...,0,NaT,CANCELLED,NaN,"1 days, 12 hours, 13 minutes",2026-02-02 12:00:00,Could not locate shop,Bongchie,Smoking Accessories,Rolling Paper
2,2026-01-31,2026-02-02,23:46:26,26013101481,NaN,NaN,HB011,Rapid Enterprises,USR-169429,Wholesaler,...,0,NaT,CANCELLED,NaN,"1 days, 12 hours, 13 minutes",2026-02-02 12:00:00,Could not locate shop,Hell Energy Drink,Beverage,Energy Drinks
3,2026-01-31,2026-02-02,23:46:26,26013101481,NaN,NaN,HB011,Rapid Enterprises,USR-169429,Wholesaler,...,0,NaT,CANCELLED,NaN,"1 days, 12 hours, 13 minutes",2026-02-02 12:00:00,Could not locate shop,Kopiko Candy,Confectionery,Kopiko candy
4,2026-01-31,2026-02-02,23:46:26,26013101481,NaN,NaN,HB011,Rapid Enterprises,USR-169429,Wholesaler,...,0,NaT,CANCELLED,NaN,"1 days, 12 hours, 13 minutes",2026-02-02 12:00:00,Could not locate shop,Alpenliebe,Confectionery,Gummies

In [2]:
df.columns

Index(['createdAt', 'deliveryDate', 'orderTime', 'orderNumber',
       'callingAgentId', 'callingAgentName', 'hubId', 'hubName', 'customerId',
       'shopType', 'retailerType', 'orderSource', 'skuNumber', 'productType',
       'itemName', 'unitType', 'unitWeight', 'orderQty', 'packedQuantity',
       'packedTime', 'deliveredQty', 'deliveredTime', 'orderStatus',
       'skuStatus', 'orderToDeliveryTime', 'deliveryTimeSlot',
       'cancellationReason', 'brand', 'category', 'subCategory'],
      dtype='str')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4999 entries, 0 to 4998
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   createdAt            4999 non-null   datetime64[us]
 1   deliveryDate         4999 non-null   datetime64[us]
 2   orderTime            4999 non-null   object
 3   orderNumber          4999 non-null   int64
 4   callingAgentId       2168 non-null   str
 5   callingAgentName     2168 non-null   str
 6   hubId                4999 non-null   str
 7   hubName              4999 non-null   str
 8   customerId           4999 non-null   str
 9   shopType             4999 non-null   str
 10  retailerType         4976 non-null   str
 11  orderSource          4999 non-null   str
 12  skuNumber            4999 non-null   str
 13  productType          4999 non-null   str
 14  itemName             4999 non-null   str
 15  unitType             0 non-null      float64
 16  unitWeight           4999 non-null   int64
 17  orderQty             4999 non-null   int64
 18  packedQuantity       4999 non-null   int64
 19  packedTime           4798 non-null   datetime64[us]
 20  deliveredQty         4999 non-null   int64
 21  deliveredTime        4348 non-null   datetime64[us]
 22  orderStatus          4999 non-null   str
 23  skuStatus            4348 non-null   str
 24  orderToDeliveryTime  4999 non-null   str
 25  deliveryTimeSlot     4999 non-null   datetime64[us]
 26  cancellationReason   1004 non-null   str
 27  brand                4999 non-null   str
 28  category             4999 non-null   str
 29  subCategory          4999 non-null   str
dtypes: datetime64[us](5), float64(1), int64(5), object(1), str(18)
memory usage: 2.1+ MB

In [4]:
df["orderStatus"].value_counts()

orderStatus
Delivered             3208
PartiallyDelivered    1140
CANCELLED              651
Name: count, dtype: int64

In [5]:
df.shape

(4999, 30)

In [6]:
df.head()

,createdAt,deliveryDate,orderTime,orderNumber,callingAgentId,callingAgentName,hubId,hubName,customerId,shopType,...,deliveredQty,deliveredTime,orderStatus,skuStatus,orderToDeliveryTime,deliveryTimeSlot,cancellationReason,brand,category,subCategory
0,2026-01-31,2026-02-02,23:55:02,26013101482,NaN,NaN,HB011,Rapid Enterprises,USR-169747,General B,...,1,2026-02-02 16:42:00,Delivered,DELIVERED,"1 days, 16 hours, 47 minutes",2026-02-02 09:00:00,NaN,Rajnigandha,Pan Masala,Premium Pan Masala
1,2026-01-31,2026-02-02,23:46:26,26013101481,NaN,NaN,HB011,Rapid Enterprises,USR-169429,Wholesaler,...,0,NaT,CANCELLED,NaN,"1 days, 12 hours, 13 minutes",2026-02-02 12:00:00,Could not locate shop,Bongchie,Smoking Accessories,Rolling Paper
2,2026-01-31,2026-02-02,23:46:26,26013101481,NaN,NaN,HB011,Rapid Enterprises,USR-169429,Wholesaler,...,0,NaT,CANCELLED,NaN,"1 days, 12 hours, 13 minutes",2026-02-02 12:00:00,Could not locate shop,Hell Energy Drink,Beverage,Energy Drinks
3,2026-01-31,2026-02-02,23:46:26,26013101481,NaN,NaN,HB011,Rapid Enterprises,USR-169429,Wholesaler,...,0,NaT,CANCELLED,NaN,"1 days, 12 hours, 13 minutes",2026-02-02 12:00:00,Could not locate shop,Kopiko Candy,Confectionery,Kopiko candy
4,2026-01-31,2026-02-02,23:46:26,26013101481,NaN,NaN,HB011,Rapid Enterprises,USR-169429,Wholesaler,...,0,NaT,CANCELLED,NaN,"1 days, 12 hours, 13 minutes",2026-02-02 12:00:00,Could not locate shop,Alpenliebe,Confectionery,Gummies

In [7]:
print("Retailers:", df["customerId"].nunique())
print("Products:", df["skuNumber"].nunique())
print("Orders:", df["orderNumber"].nunique())
print("Categories:", df["category"].nunique())

Retailers: 1494
Products: 161
Orders: 1802
Categories: 16

In [8]:
df_clean = df[
    df["orderStatus"].isin(
        ["Delivered", "PartiallyDelivered"]
    )
].copy()

print(df_clean.shape)

(4348, 30)

In [9]:
df_clean["effective_qty"] = df_clean.apply(
    lambda row:
    row["deliveredQty"]
    if row["orderStatus"] == "PartiallyDelivered"
    else row["orderQty"],
    axis=1
)

df_clean[
    ["orderQty",
     "deliveredQty",
     "effective_qty"]
].head()

    orderQty  deliveredQty  effective_qty
0          1             1              1
9          1             1              1
10         1             1              1
11         1             0              0
12         1             1              1

In [10]:
df_clean = df_clean[
    df_clean["effective_qty"] > 0
]

print(df_clean.shape)

(4048, 31)

In [11]:
df_clean["createdAt"] = pd.to_datetime(
    df_clean["createdAt"]
)

print(
    df_clean["createdAt"].min()
)

print(
    df_clean["createdAt"].max()
)

2026-01-30 00:00:00
2026-01-31 00:00:00

In [12]:
df_clean.to_parquet(
    "../data/processed/orders_clean.parquet",
    index=False
)

print("Saved successfully")

Saved successfully

In [13]:
df_clean.shape

(4048, 31)

In [14]:
df_clean.head()

,createdAt,deliveryDate,orderTime,orderNumber,callingAgentId,callingAgentName,hubId,hubName,customerId,shopType,...,deliveredTime,orderStatus,skuStatus,orderToDeliveryTime,deliveryTimeSlot,cancellationReason,brand,category,subCategory,effective_qty
0,2026-01-31,2026-02-02,23:55:02,26013101482,NaN,NaN,HB011,Rapid Enterprises,USR-169747,General B,...,2026-02-02 16:42:00,Delivered,DELIVERED,"1 days, 16 hours, 47 minutes",2026-02-02 09:00:00,NaN,Rajnigandha,Pan Masala,Premium Pan Masala,1
9,2026-01-31,2026-02-02,23:00:47,26013101480,NaN,NaN,HB011,Rapid Enterprises,USR-163237,Paan A,...,2026-02-02 14:17:00,PartiallyDelivered,DELIVERED,"1 days, 15 hours, 16 minutes",2026-02-02 09:00:00,NaN,Jabsons,Namkeen,Peanut Snacks,1
10,2026-01-31,2026-02-02,23:00:47,26013101480,NaN,NaN,HB011,Rapid Enterprises,USR-163237,Paan A,...,2026-02-02 14:17:00,PartiallyDelivered,DELIVERED,"1 days, 15 hours, 16 minutes",2026-02-02 09:00:00,NaN,Haldiram,Namkeen,Peanut Snacks,1
12,2026-01-31,2026-02-02,23:00:47,26013101480,NaN,NaN,HB011,Rapid Enterprises,USR-163237,Paan A,...,2026-02-02 14:17:00,PartiallyDelivered,DELIVERED,"1 days, 15 hours, 16 minutes",2026-02-02 09:00:00,NaN,Haldiram,Namkeen,Bhujia,1
13,2026-01-31,2026-02-02,23:00:47,26013101480,NaN,NaN,HB011,Rapid Enterprises,USR-163237,Paan A,...,2026-02-02 14:17:00,PartiallyDelivered,DELIVERED,"1 days, 15 hours, 16 minutes",2026-02-02 09:00:00,NaN,Haldiram,Namkeen,Bhujia,1