In [50]:
import pandas as pd

df = pd.read_parquet(
    "../data/processed/orders_clean.parquet"
)

print(df.shape)

(40142, 31)

In [51]:
pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (0.25.0)
Requirement already satisfied: scipy>=1.16.3 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from mlxtend) (1.17.1)
Requirement already satisfied: numpy>=2.3.5 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from mlxtend) (2.4.6)
Requirement already satisfied: pandas>=2.3.3 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from mlxtend) (3.0.3)
Requirement already satisfied: scikit-learn>=1.8.0 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from mlxtend) (1.9.0)
Requirement already satisfied: matplotlib>=3.10.8 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from mlxtend) (3.11.0)
Requirement already satisfied: joblib>=1.5.2 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (26.2)
Requirement already satisfied: pillow>=9 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from pandas>=2.3.3->mlxtend) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [52]:
baskets = (
    df.groupby("orderNumber")
    ["skuNumber"]
    .apply(list)
    .tolist()
)

len(baskets)

14898

In [53]:
from mlxtend.preprocessing import (
    TransactionEncoder
)

te = TransactionEncoder()

basket_matrix = te.fit(
    baskets
).transform(
    baskets
)

basket_df = pd.DataFrame(
    basket_matrix,
    columns=te.columns_
)

basket_df.shape

(14898, 184)

In [54]:
from mlxtend.frequent_patterns import (
    fpgrowth
)

frequent_items = fpgrowth(
    basket_df,
    min_support=0.01,
    use_colnames=True
)

frequent_items.head()

    support               itemsets
0  0.024433  frozenset({SKU00304})
1  0.020137  frozenset({SKU00009})
2  0.441200  frozenset({SKU00060})
3  0.433011  frozenset({SKU00086})
4  0.020808    frozenset({SKU799})

In [55]:
from mlxtend.frequent_patterns import (
    association_rules
)

rules = association_rules(
    frequent_items,
    metric="confidence",
    min_threshold=0.2
)

rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({SKU00086}),frozenset({SKU00060}),0.433011,0.441200,0.418513,0.966517,2.190654,1.0,0.227468,16.688971,0.958600,0.918397,0.940080,0.957547
1,frozenset({SKU00060}),frozenset({SKU00086}),0.441200,0.433011,0.418513,0.948578,2.190654,1.0,0.227468,11.026088,0.972648,0.918397,0.909306,0.957547
2,frozenset({SKU00033}),frozenset({SKU00084}),0.066922,0.181769,0.022688,0.339017,1.865095,1.0,0.010523,1.237900,0.497101,0.100386,0.192180,0.231916
3,frozenset({SKU00033}),frozenset({SKU00060}),0.066922,0.441200,0.021547,0.321966,0.729750,1.0,-0.007979,0.824147,-0.284125,0.044282,-0.213376,0.185401
4,frozenset({SKU00033}),frozenset({SKU00086}),0.066922,0.433011,0.020875,0.311936,0.720387,1.0,-0.008103,0.824035,-0.293775,0.043576,-0.213541,0.180073

In [56]:
rules = (
    rules.sort_values(
        "lift",
        ascending=False
    )
)

rules[
    [
        "antecedents",
        "consequents",
        "support",
        "confidence",
        "lift"
    ]
].head(20)

,antecedents,consequents,support,confidence,lift
98,"frozenset({SKU101, SKU00060})","frozenset({SKU00086, SKU00084})",0.027453,0.678275,9.716294
99,"frozenset({SKU00086, SKU00084})","frozenset({SKU101, SKU00060})",0.027453,0.393269,9.716294
96,"frozenset({SKU101, SKU00086})","frozenset({SKU00084, SKU00060})",0.027453,0.685092,9.494421
100,"frozenset({SKU00084, SKU00060})","frozenset({SKU101, SKU00086})",0.027453,0.380465,9.494421
45,frozenset({SKU612}),frozenset({SKU613}),0.013827,0.347386,8.254161
46,frozenset({SKU613}),frozenset({SKU612}),0.013827,0.328549,8.254161
17,"frozenset({SKU00033, SKU00060})","frozenset({SKU00086, SKU00084})",0.012284,0.570093,8.166589
15,"frozenset({SKU00086, SKU00033})","frozenset({SKU00084, SKU00060})",0.012284,0.588424,8.154742
65,"frozenset({SKUPM4, SKU00060})","frozenset({SKU00086, SKU00084})",0.013827,0.395393,5.664012
64,"frozenset({SKU00086, SKUPM4})","frozenset({SKU00084, SKU00060})",0.013827,0.400778,5.554227
95,"frozenset({SKU00086, SKU00084, SKU00060})",frozenset({SKU101}),0.027453,0.399804,5.385432
101,frozenset({SKU101}),"frozenset({SKU00086, SKU00084, SKU00060})",0.027453,0.369801,5.385432
91,frozenset({SKU101}),"frozenset({SKU00086, SKU00084})",0.027856,0.375226,5.375113
90,"frozenset({SKU00086, SKU00084})",frozenset({SKU101}),0.027856,0.399038,5.375113
83,"frozenset({SKU00084, SKU00060})",frozenset({SKU101}),0.028460,0.394419,5.312883
84,frozenset({SKU101}),"frozenset({SKU00084, SKU00060})",0.028460,0.383363,5.312883
36,frozenset({SKU00303}),frozenset({SKU00010}),0.017049,0.241445,4.055294
35,frozenset({SKU00010}),frozenset({SKU00303}),0.017049,0.286359,4.055294
82,"frozenset({SKU101, SKU00060})",frozenset({SKU00084}),0.028460,0.703151,3.868369
93,"frozenset({SKU101, SKU00086, SKU00060})",frozenset({SKU00084}),0.027453,0.701544,3.859527

In [57]:
sku_lookup = (
    df[
        [
            "skuNumber",
            "itemName"
        ]
    ]
    .drop_duplicates()
)

sku_dict = dict(
    zip(
        sku_lookup["skuNumber"],
        sku_lookup["itemName"]
    )
)

In [58]:
rules["antecedent_names"] = (
    rules["antecedents"]
    .apply(
        lambda x:
        [
            sku_dict.get(i, i)
            for i in x
        ]
    )
)

rules["consequent_names"] = (
    rules["consequents"]
    .apply(
        lambda x:
        [
            sku_dict.get(i, i)
            for i in x
        ]
    )
)

In [59]:
rules[
    [
        "antecedent_names",
        "consequent_names",
        "confidence",
        "lift"
    ]
].head(20)

,antecedent_names,consequent_names,confidence,lift
98,"[Rajnigandha 17g Zipper IC , Rajnigandha 4g ]","[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs)]",0.678275,9.716294
99,"[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs)]","[Rajnigandha 17g Zipper IC , Rajnigandha 4g ]",0.393269,9.716294
96,"[Rajnigandha 17g Zipper IC , TZ 00 (with Silve...","[TZ 00 4.25g (6 Pcs), Rajnigandha 4g ]",0.685092,9.494421
100,"[TZ 00 4.25g (6 Pcs), Rajnigandha 4g ]","[Rajnigandha 17g Zipper IC , TZ 00 (with Silve...",0.380465,9.494421
45,[Center Fruit],[Center Fresh],0.347386,8.254161
46,[Center Fresh],[Center Fruit],0.328549,8.254161
17,"[Rajnigandha 100g , Rajnigandha 4g ]","[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs)]",0.570093,8.166589
15,"[TZ 00 (with Silver) 0.45g, Rajnigandha 100g ]","[TZ 00 4.25g (6 Pcs), Rajnigandha 4g ]",0.588424,8.154742
65,"[Rajnigandha 17g Zipper 1 Pcs, Rajnigandha 4g ]","[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs)]",0.395393,5.664012
64,"[TZ 00 (with Silver) 0.45g, Rajnigandha 17g Zi...","[TZ 00 4.25g (6 Pcs), Rajnigandha 4g ]",0.400778,5.554227
95,"[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs...",[Rajnigandha 17g Zipper IC ],0.399804,5.385432
101,[Rajnigandha 17g Zipper IC ],"[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs...",0.369801,5.385432
91,[Rajnigandha 17g Zipper IC ],"[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs)]",0.375226,5.375113
90,"[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs)]",[Rajnigandha 17g Zipper IC ],0.399038,5.375113
83,"[TZ 00 4.25g (6 Pcs), Rajnigandha 4g ]",[Rajnigandha 17g Zipper IC ],0.394419,5.312883
84,[Rajnigandha 17g Zipper IC ],"[TZ 00 4.25g (6 Pcs), Rajnigandha 4g ]",0.383363,5.312883
36,[RG Pearl Elaichi 1.4g Hanger],[Pass Pass Meetha Magic 11.75g Hanger],0.241445,4.055294
35,[Pass Pass Meetha Magic 11.75g Hanger],[RG Pearl Elaichi 1.4g Hanger],0.286359,4.055294
82,"[Rajnigandha 17g Zipper IC , Rajnigandha 4g ]",[TZ 00 4.25g (6 Pcs)],0.703151,3.868369
93,"[Rajnigandha 17g Zipper IC , TZ 00 (with Silve...",[TZ 00 4.25g (6 Pcs)],0.701544,3.859527

In [60]:
print(rules.shape)

rules[
    [
        "antecedent_names",
        "consequent_names",
        "confidence",
        "lift"
    ]
].head(20)

(113, 16)

,antecedent_names,consequent_names,confidence,lift
98,"[Rajnigandha 17g Zipper IC , Rajnigandha 4g ]","[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs)]",0.678275,9.716294
99,"[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs)]","[Rajnigandha 17g Zipper IC , Rajnigandha 4g ]",0.393269,9.716294
96,"[Rajnigandha 17g Zipper IC , TZ 00 (with Silve...","[TZ 00 4.25g (6 Pcs), Rajnigandha 4g ]",0.685092,9.494421
100,"[TZ 00 4.25g (6 Pcs), Rajnigandha 4g ]","[Rajnigandha 17g Zipper IC , TZ 00 (with Silve...",0.380465,9.494421
45,[Center Fruit],[Center Fresh],0.347386,8.254161
46,[Center Fresh],[Center Fruit],0.328549,8.254161
17,"[Rajnigandha 100g , Rajnigandha 4g ]","[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs)]",0.570093,8.166589
15,"[TZ 00 (with Silver) 0.45g, Rajnigandha 100g ]","[TZ 00 4.25g (6 Pcs), Rajnigandha 4g ]",0.588424,8.154742
65,"[Rajnigandha 17g Zipper 1 Pcs, Rajnigandha 4g ]","[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs)]",0.395393,5.664012
64,"[TZ 00 (with Silver) 0.45g, Rajnigandha 17g Zi...","[TZ 00 4.25g (6 Pcs), Rajnigandha 4g ]",0.400778,5.554227
95,"[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs...",[Rajnigandha 17g Zipper IC ],0.399804,5.385432
101,[Rajnigandha 17g Zipper IC ],"[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs...",0.369801,5.385432
91,[Rajnigandha 17g Zipper IC ],"[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs)]",0.375226,5.375113
90,"[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs)]",[Rajnigandha 17g Zipper IC ],0.399038,5.375113
83,"[TZ 00 4.25g (6 Pcs), Rajnigandha 4g ]",[Rajnigandha 17g Zipper IC ],0.394419,5.312883
84,[Rajnigandha 17g Zipper IC ],"[TZ 00 4.25g (6 Pcs), Rajnigandha 4g ]",0.383363,5.312883
36,[RG Pearl Elaichi 1.4g Hanger],[Pass Pass Meetha Magic 11.75g Hanger],0.241445,4.055294
35,[Pass Pass Meetha Magic 11.75g Hanger],[RG Pearl Elaichi 1.4g Hanger],0.286359,4.055294
82,"[Rajnigandha 17g Zipper IC , Rajnigandha 4g ]",[TZ 00 4.25g (6 Pcs)],0.703151,3.868369
93,"[Rajnigandha 17g Zipper IC , TZ 00 (with Silve...",[TZ 00 4.25g (6 Pcs)],0.701544,3.859527

In [61]:
rules_save["antecedents"] = (
    rules_save["antecedents"]
    .astype(str)
)

rules_save["consequents"] = (
    rules_save["consequents"]
    .astype(str)
)

rules_save["antecedent_names"] = (
    rules_save["antecedent_names"]
    .astype(str)
)

rules_save["consequent_names"] = (
    rules_save["consequent_names"]
    .astype(str)
)

In [62]:
rules_save = rules.copy()

In [63]:
rules_save["antecedents"] = (
    rules_save["antecedents"]
    .astype(str)
)

rules_save["consequents"] = (
    rules_save["consequents"]
    .astype(str)
)

rules_save["antecedent_names"] = (
    rules_save["antecedent_names"]
    .astype(str)
)

rules_save["consequent_names"] = (
    rules_save["consequent_names"]
    .astype(str)
)

In [64]:
rules_save.to_parquet(
    "../data/processed/association_rules.parquet",
    index=False
)

print("Association rules saved")

Association rules saved

In [65]:
rules[
    [
        "antecedent_names",
        "consequent_names",
        "confidence",
        "lift"
    ]
].head(20)

,antecedent_names,consequent_names,confidence,lift
98,"[Rajnigandha 17g Zipper IC , Rajnigandha 4g ]","[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs)]",0.678275,9.716294
99,"[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs)]","[Rajnigandha 17g Zipper IC , Rajnigandha 4g ]",0.393269,9.716294
96,"[Rajnigandha 17g Zipper IC , TZ 00 (with Silve...","[TZ 00 4.25g (6 Pcs), Rajnigandha 4g ]",0.685092,9.494421
100,"[TZ 00 4.25g (6 Pcs), Rajnigandha 4g ]","[Rajnigandha 17g Zipper IC , TZ 00 (with Silve...",0.380465,9.494421
45,[Center Fruit],[Center Fresh],0.347386,8.254161
46,[Center Fresh],[Center Fruit],0.328549,8.254161
17,"[Rajnigandha 100g , Rajnigandha 4g ]","[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs)]",0.570093,8.166589
15,"[TZ 00 (with Silver) 0.45g, Rajnigandha 100g ]","[TZ 00 4.25g (6 Pcs), Rajnigandha 4g ]",0.588424,8.154742
65,"[Rajnigandha 17g Zipper 1 Pcs, Rajnigandha 4g ]","[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs)]",0.395393,5.664012
64,"[TZ 00 (with Silver) 0.45g, Rajnigandha 17g Zi...","[TZ 00 4.25g (6 Pcs), Rajnigandha 4g ]",0.400778,5.554227
95,"[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs...",[Rajnigandha 17g Zipper IC ],0.399804,5.385432
101,[Rajnigandha 17g Zipper IC ],"[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs...",0.369801,5.385432
91,[Rajnigandha 17g Zipper IC ],"[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs)]",0.375226,5.375113
90,"[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs)]",[Rajnigandha 17g Zipper IC ],0.399038,5.375113
83,"[TZ 00 4.25g (6 Pcs), Rajnigandha 4g ]",[Rajnigandha 17g Zipper IC ],0.394419,5.312883
84,[Rajnigandha 17g Zipper IC ],"[TZ 00 4.25g (6 Pcs), Rajnigandha 4g ]",0.383363,5.312883
36,[RG Pearl Elaichi 1.4g Hanger],[Pass Pass Meetha Magic 11.75g Hanger],0.241445,4.055294
35,[Pass Pass Meetha Magic 11.75g Hanger],[RG Pearl Elaichi 1.4g Hanger],0.286359,4.055294
82,"[Rajnigandha 17g Zipper IC , Rajnigandha 4g ]",[TZ 00 4.25g (6 Pcs)],0.703151,3.868369
93,"[Rajnigandha 17g Zipper IC , TZ 00 (with Silve...",[TZ 00 4.25g (6 Pcs)],0.701544,3.859527

In [66]:
rules_save = rules.copy()

for col in [
    "antecedents",
    "consequents",
    "antecedent_names",
    "consequent_names"
]:
    rules_save[col] = rules_save[col].astype(str)

rules_save.to_csv(
    "../data/processed/association_rules.csv",
    index=False
)

In [67]:
print(rules.shape)

(113, 16)

In [68]:
rules.shape

(113, 16)

In [69]:
rules.shape

(113, 16)

In [70]:
rules_save = rules.copy()

In [71]:
rules_save["antecedents"] = (
    rules_save["antecedents"]
    .astype(str)
)

rules_save["consequents"] = (
    rules_save["consequents"]
    .astype(str)
)

In [72]:
if "antecedent_names" in rules_save.columns:
    rules_save["antecedent_names"] = (
        rules_save["antecedent_names"]
        .astype(str)
    )

if "consequent_names" in rules_save.columns:
    rules_save["consequent_names"] = (
        rules_save["consequent_names"]
        .astype(str)
    )

In [73]:
rules_save.to_parquet(
    "../data/processed/association_rules.parquet",
    index=False
)

print("Saved Successfully")

Saved Successfully

In [74]:
print(rules.shape)

(113, 16)