In [1]:
import pandas as pd

df = pd.read_parquet(
    "../data/processed/orders_clean.parquet"
)

print(df.shape)

(4048, 31)

In [2]:
pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (0.25.0)
Requirement already satisfied: scipy>=1.16.3 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from mlxtend) (1.17.1)
Requirement already satisfied: numpy>=2.3.5 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from mlxtend) (2.4.6)
Requirement already satisfied: pandas>=2.3.3 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from mlxtend) (3.0.3)
Requirement already satisfied: scikit-learn>=1.8.0 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from mlxtend) (1.9.0)
Requirement already satisfied: matplotlib>=3.10.8 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from mlxtend) (3.11.0)
Requirement already satisfied: joblib>=1.5.2 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (26.2)
Requirement already satisfied: pillow>=9 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from pandas>=2.3.3->mlxtend) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\rishit\desktop\o2r-recommender\venv\lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
baskets = (
    df.groupby("orderNumber")
    ["skuNumber"]
    .apply(list)
    .tolist()
)

len(baskets)

1580

In [4]:
from mlxtend.preprocessing import (
    TransactionEncoder
)

te = TransactionEncoder()

basket_matrix = te.fit(
    baskets
).transform(
    baskets
)

basket_df = pd.DataFrame(
    basket_matrix,
    columns=te.columns_
)

basket_df.shape

(1580, 159)

In [5]:
from mlxtend.frequent_patterns import (
    fpgrowth
)

frequent_items = fpgrowth(
    basket_df,
    min_support=0.01,
    use_colnames=True
)

frequent_items.head()

    support               itemsets
0  0.018354    frozenset({SKU614})
1  0.079114  frozenset({SKU00084})
2  0.178481  frozenset({SKU00060})
3  0.173418  frozenset({SKU00086})
4  0.129747  frozenset({SKU00062})

In [6]:
from mlxtend.frequent_patterns import (
    association_rules
)

rules = association_rules(
    frequent_items,
    metric="confidence",
    min_threshold=0.2
)

rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({SKU00084}),frozenset({SKU00060}),0.079114,0.178481,0.017089,0.216000,1.210213,1.0,0.002968,1.047856,0.188622,0.071053,0.045670,0.155872
1,"frozenset({SKU00086, SKU00084})",frozenset({SKU00060}),0.011392,0.178481,0.010759,0.944444,5.291568,1.0,0.008726,14.787342,0.820366,0.060071,0.932375,0.502364
2,"frozenset({SKU00084, SKU00060})",frozenset({SKU00086}),0.017089,0.173418,0.010759,0.629630,3.630711,1.0,0.007796,2.231772,0.737169,0.059859,0.551926,0.345837
3,frozenset({SKU00086}),frozenset({SKU00060}),0.173418,0.178481,0.148101,0.854015,4.784904,1.0,0.117149,5.627405,0.956964,0.726708,0.822298,0.841901
4,frozenset({SKU00060}),frozenset({SKU00086}),0.178481,0.173418,0.148101,0.829787,4.784904,1.0,0.117149,4.856171,0.962862,0.726708,0.794076,0.841901

In [7]:
rules = (
    rules.sort_values(
        "lift",
        ascending=False
    )
)

rules[
    [
        "antecedents",
        "consequents",
        "support",
        "confidence",
        "lift"
    ]
].head(20)

,antecedents,consequents,support,confidence,lift
32,frozenset({SKUNK8}),"frozenset({SKUNK3, SKUNK2})",0.010127,0.457143,38.015038
31,"frozenset({SKUNK3, SKUNK2})",frozenset({SKUNK8}),0.010127,0.842105,38.015038
33,frozenset({SKUNK3}),"frozenset({SKUNK8, SKUNK2})",0.010127,0.347826,28.924485
30,"frozenset({SKUNK8, SKUNK2})",frozenset({SKUNK3}),0.010127,0.842105,28.924485
29,"frozenset({SKUNK8, SKUNK3})",frozenset({SKUNK2}),0.010127,0.666667,27.008547
34,frozenset({SKUNK2}),"frozenset({SKUNK8, SKUNK3})",0.010127,0.410256,27.008547
25,frozenset({SKUNK8}),frozenset({SKUNK3}),0.015190,0.685714,23.552795
26,frozenset({SKUNK3}),frozenset({SKUNK8}),0.015190,0.521739,23.552795
28,frozenset({SKUNK2}),frozenset({SKUNK8}),0.012025,0.487179,21.992674
27,frozenset({SKUNK8}),frozenset({SKUNK2}),0.012025,0.542857,21.992674
37,frozenset({SKUNK3}),frozenset({SKUNK2}),0.012025,0.413043,16.733556
38,frozenset({SKUNK2}),frozenset({SKUNK3}),0.012025,0.487179,16.733556
40,frozenset({SKU613}),frozenset({SKU612}),0.017722,0.411765,6.505882
39,frozenset({SKU612}),frozenset({SKU613}),0.017722,0.280000,6.505882
20,frozenset({SKU00075}),frozenset({SKU00010}),0.012025,0.387755,5.519397
1,"frozenset({SKU00086, SKU00084})",frozenset({SKU00060}),0.010759,0.944444,5.291568
4,frozenset({SKU00060}),frozenset({SKU00086}),0.148101,0.829787,4.784904
3,frozenset({SKU00086}),frozenset({SKU00060}),0.148101,0.854015,4.784904
8,"frozenset({SKUPM4, SKU00060})",frozenset({SKU00086}),0.013924,0.814815,4.698567
14,"frozenset({SKU00303, SKU00062})",frozenset({SKU080}),0.010759,0.346939,4.685156

In [8]:
sku_lookup = (
    df[
        [
            "skuNumber",
            "itemName"
        ]
    ]
    .drop_duplicates()
)

sku_dict = dict(
    zip(
        sku_lookup["skuNumber"],
        sku_lookup["itemName"]
    )
)

In [9]:
rules["antecedent_names"] = (
    rules["antecedents"]
    .apply(
        lambda x:
        [
            sku_dict.get(i, i)
            for i in x
        ]
    )
)

rules["consequent_names"] = (
    rules["consequents"]
    .apply(
        lambda x:
        [
            sku_dict.get(i, i)
            for i in x
        ]
    )
)

In [10]:
rules[
    [
        "antecedent_names",
        "consequent_names",
        "confidence",
        "lift"
    ]
].head(20)

,antecedent_names,consequent_names,confidence,lift
32,[Jabsons Tandoori Peanuts ],"[Jabsons Hing Jeera Peanuts, Jabsons Green Pea...",0.457143,38.015038
31,"[Jabsons Hing Jeera Peanuts, Jabsons Green Pea...",[Jabsons Tandoori Peanuts ],0.842105,38.015038
33,[Jabsons Hing Jeera Peanuts],"[Jabsons Tandoori Peanuts , Jabsons Green Peas...",0.347826,28.924485
30,"[Jabsons Tandoori Peanuts , Jabsons Green Peas...",[Jabsons Hing Jeera Peanuts],0.842105,28.924485
29,"[Jabsons Tandoori Peanuts , Jabsons Hing Jeera...",[Jabsons Green Peas onion & Garlic],0.666667,27.008547
34,[Jabsons Green Peas onion & Garlic],"[Jabsons Tandoori Peanuts , Jabsons Hing Jeera...",0.410256,27.008547
25,[Jabsons Tandoori Peanuts ],[Jabsons Hing Jeera Peanuts],0.685714,23.552795
26,[Jabsons Hing Jeera Peanuts],[Jabsons Tandoori Peanuts ],0.521739,23.552795
28,[Jabsons Green Peas onion & Garlic],[Jabsons Tandoori Peanuts ],0.487179,21.992674
27,[Jabsons Tandoori Peanuts ],[Jabsons Green Peas onion & Garlic],0.542857,21.992674
37,[Jabsons Hing Jeera Peanuts],[Jabsons Green Peas onion & Garlic],0.413043,16.733556
38,[Jabsons Green Peas onion & Garlic],[Jabsons Hing Jeera Peanuts],0.487179,16.733556
40,[Center Fresh],[Center Fruit],0.411765,6.505882
39,[Center Fruit],[Center Fresh],0.280000,6.505882
20,[Tulsi Royal Khajoor],[Pass Pass Meetha Magic 11.75g Hanger],0.387755,5.519397
1,"[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs)]",[Rajnigandha 4g ],0.944444,5.291568
4,[Rajnigandha 4g ],[TZ 00 (with Silver) 0.45g],0.829787,4.784904
3,[TZ 00 (with Silver) 0.45g],[Rajnigandha 4g ],0.854015,4.784904
8,"[Rajnigandha 17g Zipper 1 Pcs, Rajnigandha 4g ]",[TZ 00 (with Silver) 0.45g],0.814815,4.698567
14,"[RG Pearl Elaichi 1.4g Hanger, RG Pearl Elaich...",[Pass Pass Meetha Magic 2.2g (100 pcs)],0.346939,4.685156

In [12]:
rules.to_parquet(
    "../data/processed/association_rules.parquet",
    index=False
)

print("Saved")

ArrowInvalid: ("Could not convert frozenset({'SKUNK8'}) with type frozenset: did not recognize Python value type when inferring an Arrow data type", 'Conversion failed for column antecedents with type object')

In [13]:
print(rules.shape)

rules[
    [
        "antecedent_names",
        "consequent_names",
        "confidence",
        "lift"
    ]
].head(20)

(41, 16)

,antecedent_names,consequent_names,confidence,lift
32,[Jabsons Tandoori Peanuts ],"[Jabsons Hing Jeera Peanuts, Jabsons Green Pea...",0.457143,38.015038
31,"[Jabsons Hing Jeera Peanuts, Jabsons Green Pea...",[Jabsons Tandoori Peanuts ],0.842105,38.015038
33,[Jabsons Hing Jeera Peanuts],"[Jabsons Tandoori Peanuts , Jabsons Green Peas...",0.347826,28.924485
30,"[Jabsons Tandoori Peanuts , Jabsons Green Peas...",[Jabsons Hing Jeera Peanuts],0.842105,28.924485
29,"[Jabsons Tandoori Peanuts , Jabsons Hing Jeera...",[Jabsons Green Peas onion & Garlic],0.666667,27.008547
34,[Jabsons Green Peas onion & Garlic],"[Jabsons Tandoori Peanuts , Jabsons Hing Jeera...",0.410256,27.008547
25,[Jabsons Tandoori Peanuts ],[Jabsons Hing Jeera Peanuts],0.685714,23.552795
26,[Jabsons Hing Jeera Peanuts],[Jabsons Tandoori Peanuts ],0.521739,23.552795
28,[Jabsons Green Peas onion & Garlic],[Jabsons Tandoori Peanuts ],0.487179,21.992674
27,[Jabsons Tandoori Peanuts ],[Jabsons Green Peas onion & Garlic],0.542857,21.992674
37,[Jabsons Hing Jeera Peanuts],[Jabsons Green Peas onion & Garlic],0.413043,16.733556
38,[Jabsons Green Peas onion & Garlic],[Jabsons Hing Jeera Peanuts],0.487179,16.733556
40,[Center Fresh],[Center Fruit],0.411765,6.505882
39,[Center Fruit],[Center Fresh],0.280000,6.505882
20,[Tulsi Royal Khajoor],[Pass Pass Meetha Magic 11.75g Hanger],0.387755,5.519397
1,"[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs)]",[Rajnigandha 4g ],0.944444,5.291568
4,[Rajnigandha 4g ],[TZ 00 (with Silver) 0.45g],0.829787,4.784904
3,[TZ 00 (with Silver) 0.45g],[Rajnigandha 4g ],0.854015,4.784904
8,"[Rajnigandha 17g Zipper 1 Pcs, Rajnigandha 4g ]",[TZ 00 (with Silver) 0.45g],0.814815,4.698567
14,"[RG Pearl Elaichi 1.4g Hanger, RG Pearl Elaich...",[Pass Pass Meetha Magic 2.2g (100 pcs)],0.346939,4.685156

In [14]:
rules_save["antecedents"] = (
    rules_save["antecedents"]
    .astype(str)
)

rules_save["consequents"] = (
    rules_save["consequents"]
    .astype(str)
)

rules_save["antecedent_names"] = (
    rules_save["antecedent_names"]
    .astype(str)
)

rules_save["consequent_names"] = (
    rules_save["consequent_names"]
    .astype(str)
)

NameError: name 'rules_save' is not defined

In [15]:
rules_save = rules.copy()

In [16]:
rules_save["antecedents"] = (
    rules_save["antecedents"]
    .astype(str)
)

rules_save["consequents"] = (
    rules_save["consequents"]
    .astype(str)
)

rules_save["antecedent_names"] = (
    rules_save["antecedent_names"]
    .astype(str)
)

rules_save["consequent_names"] = (
    rules_save["consequent_names"]
    .astype(str)
)

In [17]:
rules_save.to_parquet(
    "../data/processed/association_rules.parquet",
    index=False
)

print("Association rules saved")

Association rules saved

In [18]:
rules[
    [
        "antecedent_names",
        "consequent_names",
        "confidence",
        "lift"
    ]
].head(20)

,antecedent_names,consequent_names,confidence,lift
32,[Jabsons Tandoori Peanuts ],"[Jabsons Hing Jeera Peanuts, Jabsons Green Pea...",0.457143,38.015038
31,"[Jabsons Hing Jeera Peanuts, Jabsons Green Pea...",[Jabsons Tandoori Peanuts ],0.842105,38.015038
33,[Jabsons Hing Jeera Peanuts],"[Jabsons Tandoori Peanuts , Jabsons Green Peas...",0.347826,28.924485
30,"[Jabsons Tandoori Peanuts , Jabsons Green Peas...",[Jabsons Hing Jeera Peanuts],0.842105,28.924485
29,"[Jabsons Tandoori Peanuts , Jabsons Hing Jeera...",[Jabsons Green Peas onion & Garlic],0.666667,27.008547
34,[Jabsons Green Peas onion & Garlic],"[Jabsons Tandoori Peanuts , Jabsons Hing Jeera...",0.410256,27.008547
25,[Jabsons Tandoori Peanuts ],[Jabsons Hing Jeera Peanuts],0.685714,23.552795
26,[Jabsons Hing Jeera Peanuts],[Jabsons Tandoori Peanuts ],0.521739,23.552795
28,[Jabsons Green Peas onion & Garlic],[Jabsons Tandoori Peanuts ],0.487179,21.992674
27,[Jabsons Tandoori Peanuts ],[Jabsons Green Peas onion & Garlic],0.542857,21.992674
37,[Jabsons Hing Jeera Peanuts],[Jabsons Green Peas onion & Garlic],0.413043,16.733556
38,[Jabsons Green Peas onion & Garlic],[Jabsons Hing Jeera Peanuts],0.487179,16.733556
40,[Center Fresh],[Center Fruit],0.411765,6.505882
39,[Center Fruit],[Center Fresh],0.280000,6.505882
20,[Tulsi Royal Khajoor],[Pass Pass Meetha Magic 11.75g Hanger],0.387755,5.519397
1,"[TZ 00 (with Silver) 0.45g, TZ 00 4.25g (6 Pcs)]",[Rajnigandha 4g ],0.944444,5.291568
4,[Rajnigandha 4g ],[TZ 00 (with Silver) 0.45g],0.829787,4.784904
3,[TZ 00 (with Silver) 0.45g],[Rajnigandha 4g ],0.854015,4.784904
8,"[Rajnigandha 17g Zipper 1 Pcs, Rajnigandha 4g ]",[TZ 00 (with Silver) 0.45g],0.814815,4.698567
14,"[RG Pearl Elaichi 1.4g Hanger, RG Pearl Elaich...",[Pass Pass Meetha Magic 2.2g (100 pcs)],0.346939,4.685156

In [19]:
rules_save = rules.copy()

for col in [
    "antecedents",
    "consequents",
    "antecedent_names",
    "consequent_names"
]:
    rules_save[col] = rules_save[col].astype(str)

rules_save.to_csv(
    "../data/processed/association_rules.csv",
    index=False
)

In [20]:
print(rules.shape)

(41, 16)

In [21]:
rules.shape

(41, 16)