In [51]:
import pandas as pd

In [52]:
retailer_features = pd.read_parquet(
    "../data/processed/retailer_features.parquet"
)

product_features = pd.read_parquet(
    "../data/processed/product_features.parquet"
)

region_trends = pd.read_parquet(
    "../data/processed/region_trends.parquet"
)

interaction = pd.read_parquet(
    "../data/processed/interaction_matrix.parquet"
)

print("Loaded Successfully")

Loaded Successfully

In [53]:
rules = pd.read_csv(
    "../data/processed/association_rules.csv"
)

rules.shape

(113, 16)

In [54]:
sku_lookup = pd.read_parquet(
    "../data/processed/sku_lookup.parquet"
)

sku_lookup.head()

  skuNumber                           itemName         brand    category
0  SKU00060                    Rajnigandha 4g   Rajnigandha   Pan Masala
1    SKUNK2  Jabsons Green Peas onion & Garlic      Jabsons      Namkeen
2   SKUNK13   Haldiram - Salted Peanuts (â‚¹5)      Haldiram     Namkeen
3    SKU501    Haldiram - Aloo Bhujia (24 pcs)      Haldiram     Namkeen
4    SKU478         Haldiram - Bhujia (24 pcs)      Haldiram     Namkeen

In [55]:
popularity_dict = dict(
    zip(
        product_features["skuNumber"],
        product_features["popularity_score"]
    )
)

In [56]:
similarity_df = pd.read_parquet(
    "../data/processed/similarity_matrix.parquet"
)

similarity_df.shape

(4480, 4480)

In [57]:
def recommend_products(
    customer_id,
    top_n=20
):
    
    similar_users = (
        similarity_df[customer_id]
        .sort_values(
            ascending=False
        )[1:11]
    )

    customer_products = set(
        interaction.loc[
            customer_id
        ][
            interaction.loc[
                customer_id
            ] > 0
        ].index
    )

    recommendations = {}

    for user in similar_users.index:

        similarity_score = (
            similar_users[user]
        )

        purchased = (
            interaction.loc[user]
        )

        for sku in purchased[
            purchased > 0
        ].index:

            if sku not in customer_products:

                recommendations[
                    sku
                ] = (
                    recommendations.get(
                        sku,
                        0
                    )
                    +
                    similarity_score
                )

    recommendations = sorted(
        recommendations.items(),
        key=lambda x: x[1],
        reverse=True
    )

    return recommendations[:top_n]

In [58]:
customer_id = interaction.index[0]

cf_recs = recommend_products(
    customer_id,
    top_n=20
)

cf_scores = {
    sku: score
    for sku, score in cf_recs
}

cf_scores

{'SKU00303': np.float64(2.775445047180592),
 'SKU080': np.float64(2.767108151738606),
 'SKU00022': np.float64(0.9128709291752768)}

In [59]:
max_cf = max(
    cf_scores.values()
)

cf_scores = {
    sku: score / max_cf
    for sku, score in cf_scores.items()
}

cf_scores

{'SKU00303': np.float64(1.0),
 'SKU080': np.float64(0.9969961950965469),
 'SKU00022': np.float64(0.3289097473223646)}

In [60]:
customer_profile = retailer_features[
    retailer_features["customerId"]
    == customer_id
]

customer_profile

,customerId,total_orders,total_qty,unique_products,last_order,first_order,shop_type,retailer_type,hub_name,days_since_last_order,favorite_category,favorite_brand,spend_segment
0,USR-100,2,4,4,2026-01-21,2026-01-20,Paan A,HVLF,Crossline Events (Noida),10,Mouth Fresheners,Rajnigandha,Low

In [61]:
hub = customer_profile[
    "hub_name"
].iloc[0]

shop_type = customer_profile[
    "shop_type"
].iloc[0]

print(hub)
print(shop_type)

Crossline Events (Noida)
Paan A

In [62]:
region_recs = region_trends[
    (
        region_trends["hubName"]
        == hub
    )
    &
    (
        region_trends["shopType"]
        == shop_type
    )
]

In [63]:
region_scores = {}

max_rank = (
    region_recs[
        "region_rank"
    ].max()
)

for _, row in region_recs.iterrows():

    score = (
        max_rank -
        row["region_rank"]
    ) / max_rank

    region_scores[
        row["skuNumber"]
    ] = score

len(region_scores)

72

In [64]:
pop_scores = popularity_dict

In [65]:
all_skus = set()

all_skus.update(
    cf_scores.keys()
)

all_skus.update(
    region_scores.keys()
)

all_skus.update(
    pop_scores.keys()
)

In [66]:
hybrid_scores = {}

for sku in all_skus:

    cf = cf_scores.get(
        sku,
        0
    )

    region = region_scores.get(
        sku,
        0
    )

    popularity = pop_scores.get(
        sku,
        0
    )

    final_score = (
        0.6 * cf
        +
        0.25 * region
        +
        0.15 * popularity
    )

    hybrid_scores[
        sku
    ] = final_score
    customer_products = set(
    interaction.loc[
        customer_id
    ][
        interaction.loc[
            customer_id
        ] > 0
    ].index
)

for sku in list(hybrid_scores.keys()):

    if sku in customer_products:

        hybrid_scores.pop(
            sku,
            None
        )

In [67]:
final_recommendations = sorted(
    hybrid_scores.items(),
    key=lambda x: x[1],
    reverse=True
)

final_recommendations[:10]

[('SKU00303', np.float64(0.7808662431318681)),
 ('SKU080', np.float64(0.7567528338161699)),
 ('SKU00022', np.float64(0.2944251753164957)),
 ('SKU00084', np.float64(0.23787688873626375)),
 ('SKUPM4', np.float64(0.2257228708791209)),
 ('SKU00033', np.float64(0.19182692307692306)),
 ('SKU101', np.float64(0.13808550824175825)),
 ('SKU669', np.float64(0.1278064903846154)),
 ('SKU00075', np.float64(0.1057967032967033)),
 ('SKU00304', np.float64(0.10542839972527474))]

In [68]:
sku_dict = dict(
    zip(
        sku_lookup["skuNumber"],
        sku_lookup["itemName"]
    )
)

for sku, score in final_recommendations[:10]:

    print(
        sku_dict.get(
            sku,
            sku
        ),
        round(score, 3)
    )

RG Pearl Elaichi 1.4g Hanger 0.781
Pass Pass Meetha Magic 2.2g (100 pcs) 0.757
Pulse Kachha Aam 175 Candy 0.294
TZ 00 4.25g (6 Pcs) 0.238
Rajnigandha 17g Zipper 1 Pcs 0.226
Rajnigandha 100g  0.192
Rajnigandha 17g Zipper IC  0.138
Alpenliebe Creamfills Butter Toffee 0.128
Tulsi Royal Khajoor 0.106
RG Pearl Elaichi Hanger (6 pcs) 0.105

In [69]:
final_recommendations[:10]

[('SKU00303', np.float64(0.7808662431318681)),
 ('SKU080', np.float64(0.7567528338161699)),
 ('SKU00022', np.float64(0.2944251753164957)),
 ('SKU00084', np.float64(0.23787688873626375)),
 ('SKUPM4', np.float64(0.2257228708791209)),
 ('SKU00033', np.float64(0.19182692307692306)),
 ('SKU101', np.float64(0.13808550824175825)),
 ('SKU669', np.float64(0.1278064903846154)),
 ('SKU00075', np.float64(0.1057967032967033)),
 ('SKU00304', np.float64(0.10542839972527474))]

In [70]:
import pandas as pd

similarity_df = pd.read_parquet(
    "../data/processed/similarity_matrix.parquet"
)

similarity_df.shape

(4480, 4480)

In [71]:
import joblib

joblib.dump(
    similarity_df,
    "../models/similarity_matrix.pkl"
)

print("Saved")

Saved

In [72]:
def hybrid_recommend(
    customer_id,
    top_n=10
):
    
    # all hybrid logic
    
    return final_recommendations[:top_n]

In [73]:
def hybrid_recommend(customer_id, top_n=10):

    cf_recs = recommend_products(
        customer_id,
        top_n=20
    )

    cf_scores = {
        sku: score
        for sku, score in cf_recs
    }

    max_cf = max(cf_scores.values())

    cf_scores = {
        sku: score / max_cf
        for sku, score in cf_scores.items()
    }

    customer_profile = retailer_features[
        retailer_features["customerId"]
        == customer_id
    ]

    hub = customer_profile[
        "hub_name"
    ].iloc[0]

    shop_type = customer_profile[
        "shop_type"
    ].iloc[0]

    region_recs = region_trends[
        (
            region_trends["hubName"]
            == hub
        )
        &
        (
            region_trends["shopType"]
            == shop_type
        )
    ]

    region_scores = {}

    max_rank = region_recs[
        "region_rank"
    ].max()

    for _, row in region_recs.iterrows():

        region_scores[
            row["skuNumber"]
        ] = (
            max_rank -
            row["region_rank"]
        ) / max_rank

    pop_scores = popularity_dict

    all_skus = set()

    all_skus.update(cf_scores.keys())
    all_skus.update(region_scores.keys())
    all_skus.update(pop_scores.keys())

    hybrid_scores = {}

    customer_products = set(
        interaction.loc[
            customer_id
        ][
            interaction.loc[
                customer_id
            ] > 0
        ].index
    )

    for sku in all_skus:

        if sku in customer_products:
            continue

        cf = cf_scores.get(sku, 0)
        region = region_scores.get(sku, 0)
        popularity = pop_scores.get(sku, 0)

        final_score = (
            0.6 * cf
            + 0.25 * region
            + 0.15 * popularity
        )

        hybrid_scores[sku] = final_score

    return sorted(
        hybrid_scores.items(),
        key=lambda x: x[1],
        reverse=True
    )[:top_n]

In [74]:
hybrid_recommend(
    interaction.index[0]
)

[('SKU00303', np.float64(0.7808662431318681)),
 ('SKU080', np.float64(0.7567528338161699)),
 ('SKU00022', np.float64(0.2944251753164957)),
 ('SKU00084', np.float64(0.23787688873626375)),
 ('SKUPM4', np.float64(0.2257228708791209)),
 ('SKU00033', np.float64(0.19182692307692306)),
 ('SKU101', np.float64(0.13808550824175825)),
 ('SKU669', np.float64(0.1278064903846154)),
 ('SKU00075', np.float64(0.1057967032967033)),
 ('SKU00304', np.float64(0.10542839972527474))]